# Change these first
owner: mail-ecnu # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: MAIL-ECNU Overleaf
    url: $SECRET_SITE

assignees:
  - 2014CAIS01
  - cww97

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://mail-ecnu.github.io/images/console_mail.jpg
  name: MAIL-ECNU uptime
  navbar:
    - title: Home
      href: https://mail-ecnu.github.io
    - title: GitHub
      href: https://github.com/mail-ecnu

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
